[project]
name = "data-structures-python"
version = "0.1.0"
description = "ADHD-friendly 21-day data structures plan"
requires-python = ">=3.10"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"